---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
- name: ubuntu-14.04
  run_list:
  - recipe[apt]

suites:
  - name: default
    run_list: 
      - recipe[301::default]
      - recipe[301::upstart]
    attributes:
